// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "GoDigit",
  platforms: [
    .iOS("16.0"),
  ],
  products: [
    .iOSApplication(
      name: "GoDigit",
      targets: ["AppModule"],
      bundleIdentifier: "moe.rewired.Go-Digit",
      teamIdentifier: "G3DZDVUX5D",
      displayVersion: "1.0",
      bundleVersion: "1",
      appIcon: .placeholder(icon: .magicWand),
      accentColor: .presetColor(.green),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ],
      appCategory: .developerTools
    ),
  ],
  dependencies: [
    .package(url: "https://github.com/attaswift/BigInt.git", "5.1.0" ..< "6.0.0"),
    .package(url: "https://github.com/colinc86/LaTeXSwiftUI", .branch("main")),
    .package(url: "https://github.com/joogps/SlideOverCard", "2.1.0" ..< "3.0.0"),
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      dependencies: [
        .product(name: "BigInt", package: "bigint"),
        .product(name: "LaTeXSwiftUI", package: "latexswiftui"),
        .product(name: "SlideOverCard", package: "slideovercard"),
      ],
      path: "."
    ),
  ]
)
